### ISSUE TITLE
GFP and segmentation calculations

### ISSUE THREAD

**Issue by DraganaMana** [wmvanvliet/mne_microstates#4]
Hello Marijn,

I have a couple of questions regarding the code. 

According to formulas and how it's calculated in the [EEGLab microstate toolbox](https://github.com/atpoulsen/Microstate-EEGlab-toolbox/blob/52a94e647748efb26091328be51079f45d451b9e/MST1.0/modkmeans.m#L118) (GFP = std(X)), should there be an additional square root when calculating the gfp (line 88)? 
https://github.com/wmvanvliet/mne_microstates/blob/dbca41a2dda93b36b7f4ff4e8fe700c879b999b4/microstates.py#L88

Furthermore, I didn't understand why is there a difference between line 113 and line 150? 
https://github.com/wmvanvliet/mne_microstates/blob/dbca41a2dda93b36b7f4ff4e8fe700c879b999b4/microstates.py#L112-L114
https://github.com/wmvanvliet/mne_microstates/blob/dbca41a2dda93b36b7f4ff4e8fe700c879b999b4/microstates.py#L149-L151

Thank you again for your work and your time! 
Dragana

**Comment by wmvanvliet** [comment]
Proper GFP should indeed have a square root in there. I think I omitted it because it was only used for peak picking, which should work fine on the squared version too. Same goes for the difference between lines 113 and 150, there are equivalent since we only care about the argmax.

However, it is not very neat to leave things this way. Fixed in master! Thank you for raising the issue.
